name: truncate
description: String truncation library supporting predefined and custom truncation strategies
version: 3.0.1
homepage: https://github.com/aquilax/truncate-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
  benchmark_harness: ^2.0.0
  lints: ^2.0.0
